spring:
  application:
    name: kanban
  datasource:
    url: jdbc:postgresql://localhost:5432/kanban_db
    username: kanban_user
    password: kanban_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration