services:
  postgres:
    image: postgres:15
    container_name: kanban-postgres
    environment:
      POSTGRES_DB: kanban_db
      POSTGRES_USER: kanban_user
      POSTGRES_PASSWORD: kanban_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kanban_user -d kanban_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  kanban-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: kanban-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kanban_db
      SPRING_DATASOURCE_USERNAME: kanban_user
      SPRING_DATASOURCE_PASSWORD: kanban_pass
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  postgres_data: